### ISSUE TITLE
Questions about sensor and installation

### ISSUE THREAD

**Issue by LUCKandII** [Miramaksimus/HOTAS-Joystick-Soleil#1]
Great job and thanks for your sharing!I have some question about the sensor and would you mind give me some answers?
* You mentioned 2 unit TLE5011/5010 sensors and 1 unit Hall-effect sensor in your project, I wonder which of these is for z axis?
* How to inatall z axis magnet?I don't see room to mount magnets and sensors. Can you share some pictures of the installation?
* TLE5011/5012 sensor use SPI bus for communication.Dose freejoy support 2 or more SPI device? In the configure page, it seems there's no distinction two different spi devices... Would you mind to share some key config (files/picture/anything else) about this?
* How do these two pieces fit together?If I use screws, it seems that it can't be twisted.

Thank you in advance for your help!

![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/78e2d667-76a6-4f4f-a2f6-5a573d7c0049)

![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/2adeb2f6-ff08-4d4a-8c2c-5fe5d98a5767)

**Comment by Miramaksimus** [comment]
Here are the fixed answers:

1. The TLE5011/5010 sensors are utilized for the X and Y axes, as demonstrated in the video (https://youtu.be/IS1_Lb0nVMM?t=363). For the Z-axis, a Hall-effect sensor is employed (image1) -use hot glue to secure the sensor position.
2. For guidance on installing the Z-axis magnets, refer to the available images demonstrating the installation process (image2 and image3).
3. For configuring the TLE5011/5010 sensors (not the TLE5012), please find my configuration details in image4.
4. If you wish to disable the twisting functionality, screws are provided for this purpose. However, if you want to enable twisting, it is recommended to use super glue for assembly. Secure the twist's bottom part with super glue to the bearing, assemble the twist, check for proper functionality, and then attach the top twist part with super glue to the inside of the bearing. This method ensures a secure assembly while allowing the necessary twisting motion. (See how to install the bearing: https://youtu.be/IS1_Lb0nVMM?t=381)

For more in-depth information and insights from the community, it is advised to check the description, comments, and responses on the Thingiverse page (https://www.thingiverse.com/thing:5976575). Exploring remixed versions and related content on Thingiverse can also provide valuable tips, modifications, and community feedback.

Additionally, you can find helpful visual guides and demonstrations related to joysticks on my YouTube channel (https://www.youtube.com/watch?v=4qccZbGVc9M&list=PL6WOn1wgybe4zLbwNDsI1c768gBqbFAPy&index=4).

image1

![IMG_20230503_011742](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/8ca0b2be-90fc-4c80-9cc9-00069dccb939)

image2
![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/400886ff-f22a-4c3c-8239-d4b90b343a21)

image3
![Screenshot_12](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/f214bed5-8925-45b7-9ab5-beaf37c1b82c)

image4
![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/74d31b17-334f-45d0-af64-9d75ff19f0be)

**Comment by LUCKandII** [comment]
> Hello,
> 
> Here are the answers to your questions:
> 
> 1. The TLE5011/5010 sensors are utilized for the X and Y axes, as demonstrated in the video (https://youtu.be/IS1_Lb0nVMM?t=363). For the Z-axis, a Hall-effect sensor is employed (image1) -use hot glue to secure the sensor position.
> 2. For guidance on installing the Z-axis magnets, refer to the available images demonstrating the installation process (image2 and image3).
> 3. For configuring the TLE5011/5010 sensors (not the TLE5012), please find my configuration details in image4.
> 4. If you wish to disable the twisting functionality, screws are provided for this purpose. However, if you want to enable twisting, it is recommended to use super glue for assembly. Secure the twist's bottom part with super glue to the bearing, assemble the twist, check for proper functionality, and then attach the top twist part with super glue to the inside of the bearing. This method ensures a secure assembly while allowing the necessary twisting motion. (See how to install the bearing: https://youtu.be/IS1_Lb0nVMM?t=381)
> 
> For more in-depth information and insights from the community, it is advised to check the description, comments, and responses on the Thingiverse page (https://www.thingiverse.com/thing:5976575). Exploring remixed versions and related content on Thingiverse can also provide valuable tips, modifications, and community feedback.
> 
> Additionally, you can find helpful visual guides and demonstrations related to joysticks on my YouTube channel (https://www.youtube.com/watch?v=4qccZbGVc9M&list=PL6WOn1wgybe4zLbwNDsI1c768gBqbFAPy&index=4).
> 
> image1
> 
> ![IMG_20230503_011742](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/8ca0b2be-90fc-4c80-9cc9-00069dccb939)
> 
> image2
> ![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/400886ff-f22a-4c3c-8239-d4b90b343a21)
> 
> image3
> ![Screenshot_12](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/f214bed5-8925-45b7-9ab5-beaf37c1b82c)
> 
> image4
> ![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/74d31b17-334f-45d0-af64-9d75ff19f0be)
> 
> 
> 

Thank you! I've prepared all 3d printed components and "shopping list".  I think the best way to thank you is to recreate your work!
