### ISSUE TITLE
Question about wiring hardware connection

### ISSUE THREAD

**Issue by LUCKandII** [Miramaksimus/HOTAS-Joystick-Soleil#2]
Hi, I've watched your youtube video and your thingiverse page and really learned a lot! I also have some questions about wiring hardware connection:

* How to connect 4/5-way Switch to stm32 blue pill? Do you use 4/5-way Switch as keyboard array? Would you mind to share some more information about this?

* It makes me more curious about your wiring that you flight stick is replaceably with pogopin! It seems impossible to connect all the switch on the stick with only 10 pogopins (showed in the video) since it has FOUR 4/5-way switch and TWO push buttons because 4/5-way switch has at least 4 pin for each and push has at least 1 pin for each.Do you used resistance to make 4/5-way switcs as analog output? Would you mind to share more information about you pogopin design?

![Screenshot_2024-01-27-09-48-55-813_com.google.android.youtube.jpg](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/882683ab-9715-41aa-b27b-2e41f9b77259)

**Comment by Miramaksimus** [comment]
Hi, there is one answer to your two questions - a matrix of buttons. You can find more details [here](https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/Connecting-buttons-directly-to-controller.md).

![image](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/88786fb9-3cda-48ea-9187-efe64e161977)

With a 5x5 matrix, you can connect 25 buttons on the F-16 stick:

- three 5-way switches
- one 4-way switch
- 6 buttons

In the screenshot with the pin configuration from your previous issue, you can see a 5x6 matrix configured, which allows connecting 30 buttons (25 on the stick and 5 on the base of SOLEIL).

[The WiKi of the FreeJoy project](https://github.com/FreeJoy-Team/FreeJoyWiki/tree/master) could be useful for you.

**Comment by LUCKandII** [comment]
Thanks for your help! I couldn't wait to share my joystick to you!
![1000012699](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/df7ef069-b023-4bdc-b04c-dadd48d03fa9)
![1000012700](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/fe9db7c2-2d38-43e6-8a9b-feb0b18bd15a)
![1000012701](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/421a5d77-4dad-45a6-8af6-45d2ac85e38a)
![1000012705](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/02b718bc-bc69-4e15-8511-56ec3dc625d0)

**Comment by Miramaksimus** [comment]
You are welcome! It is amazing make! If you wont you can post your make in https://www.thingiverse.com/thing:5976575

I uploaded short video that can help you with trigger:

https://www.youtube.com/shorts/-YpK8iMiVb8

[![ short video](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/61583858/518dc419-c8c3-4701-adf3-2799bff57d8f)](https://www.youtube.com/shorts/-YpK8iMiVb8)

**Comment by LUCKandII** [comment]
Thanks a lot! I fixed my trigger finally and made a [throttle-quadrant](https://github.com/Miramaksimus/throttle-quadrant-fokker-8-axes-and-31-buttons) these day! So excited to share with you!
![1000012962](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/beac7577-faa7-49f9-a62b-cf8dbe57c3af)
![1000012968](https://github.com/Miramaksimus/HOTAS-Joystick-Soleil/assets/44010936/16425ecc-c859-468b-a22d-63b65997f7b7)
I have a new question now... I connected stick and throttle to PC and running DCS, but one of my freejoy device setting is invalid. Did you use both stick and throttle in the same time and meet similar problem? I guess it might have something to do with the freejoy USB VID and PID https://github.com/FreeJoy-Team/FreeJoy/issues/209#issuecomment-1975108704.  I tried to modify USB VID and PID but this problem still unsolved. Do you have any ideas?

**Comment by LUCKandII** [comment]
Well... Modifying USB VID and PID does work! All needed to do is restart DCS program!
I will post my making to thingivese later!

**Comment by LUCKandII** [comment]
@Miramaksimus 
Here is my make!
https://www.thingiverse.com/make:1165394
https://www.thingiverse.com/make:1165395

**Comment by Miramaksimus** [comment]
Thank you!

**Comment by Ahmet0691** [comment]
Can you share a photo of the direction of the diode facing the key? What is the name of the connectors you are using? And what is the task of bringing the joystick back to the center point, is it a spring or a rubber? [Is the diode looking at the chip or the button?]

**Comment by LUCKandII** [comment]
> Can you share a photo of the direction of the diode facing the key? What is the name of the connectors you are using? And what is the task of bringing the joystick back to the center point, is it a spring or a rubber? [Is the diode looking at the chip or the button?]

* A photo of the direction of the diode facing the key. I made a key matrix PCB and all diodes are weilding on it. The diode is IN4148W, SOD-123 footprint.
* Any wire-to-wire connector is fine as long as it's easy to buy. I don't have an exact name of my connector... It's just some kind of 1.25mm 6P wire-to-wire connector.
* Joystick back to the center point using spring. [This video gives more information](https://www.youtube.com/watch?v=IS1_Lb0nVMM)
![image](https://github.com/user-attachments/assets/d4867c66-45e4-4d90-bcbf-9085caa24383)
![image](https://github.com/user-attachments/assets/f494bc50-15f2-4551-b921-63957fd1df07)

**Comment by SirPotatoCat** [comment]
> Thanks for your help! I couldn't wait to share my joystick to you! It works perfect except the trigger botton.I will try to fix it. Your throttle quadrant is my next goal! ![1000012699](https://private-user-images.githubusercontent.com/44010936/308768615-df7ef069-b023-4bdc-b04c-dadd48d03fa9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTcwMjEsIm5iZiI6MTczNDc1NjcyMSwicGF0aCI6Ii80NDAxMDkzNi8zMDg3Njg2MTUtZGY3ZWYwNjktYjAyMy00YmRjLWIwNGMtZGFkZDQ4ZDAzZmE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNjFmYTMyOWNiZWMwZTdhOGIyMzEwM2E2NzA0NGM0MTI5ZWZlMjE0NWQ2OGQwMDAxOTY1OThlOTdhMjk4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.90uzBYC3U8BkuODUDMNFW616FK2KdH3lR4_CbfUFY_s) ![1000012700](https://private-user-images.githubusercontent.com/44010936/308768640-fe9db7c2-2d38-43e6-8a9b-feb0b18bd15a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTcwMjEsIm5iZiI6MTczNDc1NjcyMSwicGF0aCI6Ii80NDAxMDkzNi8zMDg3Njg2NDAtZmU5ZGI3YzItMmQzOC00M2U2LThhOWItZmViMGIxOGJkMTVhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OTgzYjA3YjVhYWI4Zjc0ZGM4NWUxNmNmMzQzYzc4ZjBlNGM2N2U4MDhiZDBhZTRlN2FiZGQ2MTAyYzM3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QOObZoUW0W-rbeOyoteCcZWYeJPOxr3-gqYtw90GU5U) ![1000012701](https://private-user-images.githubusercontent.com/44010936/308768654-421a5d77-4dad-45a6-8af6-45d2ac85e38a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTcwMjEsIm5iZiI6MTczNDc1NjcyMSwicGF0aCI6Ii80NDAxMDkzNi8zMDg3Njg2NTQtNDIxYTVkNzctNGRhZC00NWE2LThhZjYtNDVkMmFjODVlMzhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDA0Yzk3MWY3YTkwOWYyN2E3ZjBiZWU0ODRmN2JiMzFiMGRjYjNhZjE3NDZmNTg0YjdmYWE2NzU4ZjRkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wkkIuVs3vPTXKXwElC7QblQUfFu6E4El3RqwuuJUdpI) ![1000012705](https://private-user-images.githubusercontent.com/44010936/308768666-02b718bc-bc69-4e15-8511-56ec3dc625d0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTcwMjEsIm5iZiI6MTczNDc1NjcyMSwicGF0aCI6Ii80NDAxMDkzNi8zMDg3Njg2NjYtMDJiNzE4YmMtYmM2OS00ZTE1LTg1MTEtNTZlYzNkYzYyNWQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0NTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmFkNWZlOWU1YjRlMzRlZGJiZDIzNjQ4ZmMyMWY0YTAzZWE0NmRiYjY5MjYyYzY3Y2E3MzNmY2VlMWQxYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MIFe4CtfAQaN-9XCStXSxRsFo1Lx91GVUcZn0wysvBg)


I'm looking forward to building this, I have all the parts ready to order but i was wondering if you knew which screws is should order? The originally model he remixed this from seemed to just screw right into the plastic but in his video he has nuts?

**Comment by LUCKandII** [comment]
> I'm looking forward to building this, I have all the parts ready to order but i was wondering if you knew which screws is should order? The originally model he remixed this from seemed to just screw right into the plastic but in his video he has nuts?

Nuts are necessary. Mostly M3 and M4 nuts. It's a compoment list in readme of this project.

**Comment by Miramaksimus** [comment]
> Can you share some information about joystick pogopin definition? Is it the same as warthgo HOTAS?

Yes, it is remixed from https://www.thingiverse.com/thing:3097965

**Comment by beezer2711** [comment]
> > Can you share a photo of the direction of the diode facing the key? What is the name of the connectors you are using? And what is the task of bringing the joystick back to the center point, is it a spring or a rubber? [Is the diode looking at the chip or the button?]
> 
> * A photo of the direction of the diode facing the key. I made a key matrix PCB and all diodes are weilding on it. The diode is IN4148W, SOD-123 footprint.
> * Any wire-to-wire connector is fine as long as it's easy to buy. I don't have an exact name of my connector... It's just some kind of 1.25mm 6P wire-to-wire connector.
> * Joystick back to the center point using spring. [This video gives more information](https://www.youtube.com/watch?v=IS1_Lb0nVMM)
>   ![image](https://github.com/user-attachments/assets/d4867c66-45e4-4d90-bcbf-9085caa24383)
>   ![image](https://github.com/user-attachments/assets/f494bc50-15f2-4551-b921-63957fd1df07)

LUCKandII, 

I am try to figure out how to make this board but I am not sure where to start. I also made the Fokker throttle and I need a different way to wire it and I love your design. please reach back if possible. thanks

**Comment by LUCKandII** [comment]
> > > Can you share a photo of the direction of the diode facing the key? What is the name of the connectors you are using? And what is the task of bringing the joystick back to the center point, is it a spring or a rubber? [Is the diode looking at the chip or the button?]
> > 
> > 
> > 
> > * A photo of the direction of the diode facing the key. I made a key matrix PCB and all diodes are weilding on it. The diode is IN4148W, SOD-123 footprint.
> > * Any wire-to-wire connector is fine as long as it's easy to buy. I don't have an exact name of my connector... It's just some kind of 1.25mm 6P wire-to-wire connector.
> > * Joystick back to the center point using spring. [This video gives more information](https://www.youtube.com/watch?v=IS1_Lb0nVMM)
> >   ![image](https://github.com/user-attachments/assets/d4867c66-45e4-4d90-bcbf-9085caa24383)
> >   ![image](https://github.com/user-attachments/assets/f494bc50-15f2-4551-b921-63957fd1df07)
> 
> LUCKandII,
> 
> I am try to figure out how to make this board but I am not sure where to start. I also made the Fokker throttle and I need a different way to wire it and I love your design. please reach back if possible. thanks

<img width="2912" height="1057" alt="Image" src="https://github.com/user-attachments/assets/cdad4d5c-11ec-4c19-8c94-454ec4dd2783" />

<img width="2008" height="1001" alt="Image" src="https://github.com/user-attachments/assets/54c022bd-9f36-4867-aa6c-7d282f1f7b37" />

Here is the design. See if this can help you.
